module.exports = [
  { name: 'Alabama', website_url: 'https://rolltide.com', conference: 'SEC', team: 'Crimson Tide' },
  { name: 'Auburn', website_url: 'https://auburntigers.com', conference: 'SEC', team: 'Tigers' },
  { name: 'Clemson', website_url: 'https://clemsontigers.com', conference: 'ACC', team: 'Tigers' },
  { name: 'Duke', website_url: 'https://goduke.com', conference: 'ACC', team: 'Blue Devils' },
  { name: 'Florida', website_url: 'https://floridagators.com', conference: 'SEC', team: 'Gators' },
  { name: 'Florida State', website_url: 'https://seminoles.com', conference: 'ACC', team: 'Seminoles' },
  { name: 'Georgia', website_url: 'https://georgiadogs.com', conference: 'SEC', team: 'Bulldogs' },
  { name: 'LSU', website_url: 'https://lsusports.net', conference: 'SEC', team: 'Tigers' },
  { name: 'Miami', website_url: 'https://miamihurricanes.com', conference: 'ACC', team: 'Hurricanes' },
  { name: 'Michigan', website_url: 'https://mgoblue.com', conference: 'Big Ten', team: 'Wolverines' },
  { name: 'Michigan State', website_url: 'https://msuspartans.com', conference: 'Big Ten', team: 'Spartans' },
  { name: 'Notre Dame', website_url: 'https://fightingirish.com', conference: 'Independent', team: 'Fighting Irish' },
  { name: 'Ohio State', website_url: 'https://ohiostatebuckeyes.com', conference: 'Big Ten', team: 'Buckeyes' },
  { name: 'Ole Miss', website_url: 'https://olemisssports.com', conference: 'SEC', team: 'Rebels' },
  { name: 'Oregon', website_url: 'https://goducks.com', conference: 'Big Ten', team: 'Ducks' },
  { name: 'Penn State', website_url: 'https://gopsusports.com', conference: 'Big Ten', team: 'Nittany Lions' },
  { name: 'Pittsburgh', website_url: 'https://pittsburghpanthers.com', conference: 'ACC', team: 'Panthers' },
  { name: 'South Carolina', website_url: 'https://gamecocksonline.com', conference: 'SEC', team: 'Gamecocks' },
  { name: 'Tennessee', website_url: 'https://utsports.com', conference: 'SEC', team: 'Volunteers' },
  { name: 'Texas', website_url: 'https://texassports.com', conference: 'SEC', team: 'Longhorns' },
  { name: 'Texas A&M', website_url: 'https://12thman.com', conference: 'SEC', team: 'Aggies' },
  { name: 'UCLA', website_url: 'https://uclabruins.com', conference: 'Big Ten', team: 'Bruins' },
  { name: 'USC', website_url: 'https://usctrojans.com', conference: 'Big Ten', team: 'Trojans' },
  { name: 'Virginia Tech', website_url: 'https://hokiesports.com', conference: 'ACC', team: 'Hokies' },
  { name: 'Wake Forest', website_url: 'https://godeacs.com', conference: 'ACC', team: 'Demon Deacons' }
];